name: "Pyright Type Check"

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - "**.py"
      - "pyproject.toml"
      - "pyrightconfig.json"
      - ".github/workflows/pyright-check.yml"

jobs:
  pyright-check:
    name: "Pyright Type Check"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version-file: '.python-version'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Load cached venv
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-pyright-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        run: poetry install --no-interaction --extras dev

      - name: Add Poetry venv to PATH
        run: echo "$(poetry env info --path)/bin" >> $GITHUB_PATH

      - name: Run Pyright Type Check
        uses: jakebailey/pyright-action@v2
        with:
          version: "1.1.403"  # Pin to same version as local
          working-directory: '.'
          python-platform: 'Linux'
          python-version: ${{ steps.setup-python.outputs.python-version }}
          annotate: 'all'
          warnings: true
